#!/usr/bin/env bash
# shellcheck disable=SC2154
# Configures nginx to add a custom X-Served-By response header
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i "/listen 80 default_server;/a\\    add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

service nginx start
service nginx restart
