#!/usr/bin/env bash
# Installs and configures nginx with a redirect for /redirect_me
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a\\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
service nginx start
service nginx restart
