#!/usr/bin/env bash
# Installs and configures nginx with a redirect and a custom 404 page
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server;/a\\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a\\terror_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx start
service nginx restart
